version: '3.9'
services:
  app:
    build: .
    image: hitech-market/api
    container_name: hitech-market_api
    depends_on:
      - pgsql
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME:-hitech-market}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-juswee}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-passwd}
      DATABASE_DIALECT: ${DATABASE_DIALECT}
      NODE_ENV: production
      PORT: ${PORT:-3000}
    ports:
      - "8248:${PORT}"
    networks:
      - hitech-market

  pgsql:
    image: postgres:13
    container_name: hitech-market_pgsql
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-hitech-market}
      POSTGRES_USER: ${DATABASE_USERNAME:-juswee}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-passwd}
    networks:
      - hitech-market
    volumes:
      - pgsql:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${DATABASE_NAME}",
          "-U",
          "${DATABASE_USERNAME}"
        ]
      start_period: 10s
      timeout: 5s
      retries: 5

volumes:
  app: null
  pgsql:
    driver: local

networks:
  hitech-market: null
